var new_lang = {
    "lt0": "XX<span> Fernglas </span>",
    "lt1": "16-facher <br>Zoom",
    "lt2": "Qualitativ hochwertige <br>Bilder",
    "lt3": "Bruchsicheres <br>und wasserdichtes Gehäuse",
    "lt4": "Sonderangebot endet in:",
    "lt5": "alter <br>Preis:",
    "lt6": "Dollar",
    "lt7": "Sonderangebot<br>Preis:",
    "lt8": "Dollar",
    "lt9": "Mit Rabatt bestellen",
    "lt10": "XX <span> Fernglas </span>",
    "lt11": " Sonderangebot endet in:",
    "lt12": "16-facher <br>Zoom",
    "lt13": "Qualitativ hochwertige <br>Bilder",
    "lt14": " Bruchsicheres <br> und wasserdichtes Gehäuses",
    "lt15": "alter <br>Preis:",
    "lt16": "Dollar",
    "lt17": "Sonderangebot <br>Preis:",
    "lt18": " Dollar ",
    "lt19": "Mit Rabatt bestellen",
    "lt20": "Neue Generation <br><span> super scharf </span><br><span> Fernglas </span>",
    "lt21": "Verpassen Sie <br><span>kein einziges Detail</span>",
    "lt22": "Sie sind oft in der Natur unterwegs?<br>Sie müssen Dinge in der Ferne beobachten?<b> Ein gutes Fernglas eignet sich </b> sowohl für erfahrene Jäger als auch Outdoor-Abenteurer",
    "lt23": "Wo können Sie schon <br>ohne<span>ein Fernglasr</span><br>XX auskommen?",
    "lt24": "Mit Rabatt bestellen",
    "lt25": " auf der Jagd ",
    "lt26": "erspähen Sie Tiere <br> doppelt so schnell ",
    "lt27": " in der Wildnis",
    "lt28": "Genießen Sie <br>wundervolle Landschaften",
    "lt29": "auf einem Blick",
    "lt30": "Schauen Sie sich Fußballspiele <br>von der hintersten Reihe an",
    "lt31": "Mit Rabatt bestellen",
    "lt32": "Wo können Sie schon <br>ohne<span>ein Fernglasr</span><br>XX auskommen?",
    "lt33": "auf der Jagd",
    "lt34": "erspähen Sie Tiere <br> doppelt so schnell ",
    "lt35": "in der Wildnis ",
    "lt36": "Genießen Sie <br>wundervolle Landschaften",
    "lt37": "auf einem Blick",
    "lt38": "Schauen Sie sich Fußballspiele <br>von der hintersten Reihe an ",
    "lt39": "Warum<br><span class=\"span\">dieses eine</span><span>XX?</span>",
    "lt40": "Extrem einfach zu nutzen",
    "lt41": "Ein präzises und leichtes Gerät",
    "lt42": "Super Zoom",
    "lt43": "Duale Anpassung",
    "lt44": "Mit Rabatt bestellen",
    "lt45": "Kundenmeinungen von <br><span>zufriedenen</span><span class=\"white\">Kunden</span>",
    "lt46": "Andreas, Lüneburg",
    "lt47": "Ich glaube ich habe XX zu einem fairen Preis gekauft. Die Qualität ist ziemlich gut. Das Gerät hilft mir bei der Jagd. Ich komme fast jedes Mal mit Beute zurück. Ich bin sehr zufrieden damit",
    "lt48": "Georg, Halle",
    "lt49": "Das Preis-Leistungs-Verhältnis ist in Ordnung. Das Gerät ist präzise und zuverlässig. Vorher hatte ich ein anderes gebrauchtes Gerät, das ich geschenkt bekam und das herunterfiel und auf den Steinen zerbrach. Ich habe meinen neuen XX ein paar Mal auf Reisen fallen gelassen, aber es ist nichts passiert. Ich denke, dass der Kauf dieses Fernglases die richtige Wahl war.",
    "lt50": "Jan, Dessau",
    "lt51": "Als erfahrener Kletterer habe ich zahlreiche Ferngläser ausprobiert. Für mich ist dieses XX das beste. Die Qualität ist großartig und es ist nicht teuer. Der einzige Nachteil ist, dass es schade wäre, es unterwegs zu verlieren.",
    "lt52": "Andreas, Lüneburg",
    "lt53": "Ich glaube ich habe XX zu einem fairen Preis gekauft. Die Qualität ist ziemlich gut. Das Gerät hilft mir bei der Jagd. Ich komme fast jedes Mal mit Beute zurück. Ich bin sehr zufrieden damit",
    "lt54": "Georg, Halle",
    "lt55": "Das Preis-Leistungs-Verhältnis ist in Ordnung. Das Gerät ist präzise und zuverlässig. Vorher hatte ich ein anderes gebrauchtes Gerät, das ich geschenkt bekam und das herunterfiel und auf den Steinen zerbrach. Ich habe meinen neuen XX ein paar Mal auf Reisen fallen gelassen, aber es ist nichts passiert. Ich denke, dass der Kauf dieses Fernglases die richtige Wahl war.",
    "lt56": "Jan, Dessau",
    "lt57": "Als erfahrener Kletterer habe ich zahlreiche Ferngläser ausprobiert. Für mich ist dieses XX das beste. Die Qualität ist großartig und es ist nicht teuer. Der einzige Nachteil ist, dass es schade wäre, es unterwegs zu verlieren.",
    "lt58": "Es ist ganz einfachy<br><span>eine Bestellung</span><span class=\"white-b\">aufzugeben!</span>",
    "lt59": "Bestellung",
    "lt60": "Geben Sie eine Bestellung auf,<br>indem Sie das Bestellformular ausfüllen",
    "lt61": " Ausfüllen ",
    "lt62": "Unser Experte wird Sie zurückrufeni<br>und die Bestellung bestätigen ",
    "lt63": " Erhalt ",
    "lt64": "Erhalten Sie die Bestellung <br>wie es Ihnen am besten passt",
    "lt65": "Zahlung",
    "lt66": "Zahlung per Nachnahme <br>per Bargeld oder Karte",
    "lt67": "XX<span>Fernglas</span>",
    "lt68": "16-facher <br>Zoom",
    "lt69": "Qualitativ hochwertige <br>Bilder",
    "lt70": "Bruchsicheres <br>und wasserdichtes Gehäuse",
    "lt71": "Sonderangebot endet in:",
    "lt72": "alter<br>Preis:",
    "lt73": "Dollar",
    "lt74": "Sonderangebot <br>Preis:",
    "lt75": "Dollar",
    "lt76": "Deutschland",
    "lt77": "MIT RABATT BESTELLEN",
    "lt79": "XX<span>Fernglas</span>",
    "lt80": " Sonderangebot endet in:",
    "lt81": "16-facher <br>Zoom",
    "lt82": "Qualitativ hochwertige <br>Bilder",
    "lt83": "Bruchsicheres <br>und wasserdichtes Gehäuse",
    "lt84": "alter<br>Preis:",
    "lt85": "Dollar",
    "lt86": "Sonderangebot<br>Preis:",
    "lt87": "Dollar",
    "lt88": " Deutschland ",
    "lt89": "MIT RABATT BESTELLEN",
    "lt91": "Datenschutzrichtlinie",
    "lt92": "Öffentliches Angebot"
};
function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
}
;



